# Generated by Django 4.2.20 on 2025-04-27 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reservations.models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("adresse", models.CharField(max_length=255)),
                (
                    "capacite",
                    models.CharField(
                        choices=[
                            ("6x6", "6×6"),
                            ("7x7", "7×7"),
                            ("8x8", "8×8"),
                            ("9x9", "9×9"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "prix_par_personne",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("est_ouvert", models.BooleanField(default=True)),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StadeImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=reservations.models.stade_upload_path),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "stade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reservations.stade",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
